name: Copilot IntelliJ plugin rating

on:
  schedule:
    - cron: '0 17 * * *'  # Runs every day at 1AM CST (China Standard Time is UTC+8)
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write  # Grant write permission to contents

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set current time
      id: set_time
      run: echo "CURRENT_TIME=$(TZ='Asia/Shanghai' date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

    - name: Fetch data from URL
      run: |
        curl -o "copilot-intellij/data_${{ env.CURRENT_TIME }}.json" https://plugins.jetbrains.com/api/plugins/17718/rating

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add "copilot-intellij/data_${{ env.CURRENT_TIME }}.json"
        git commit -m "Update data.json with latest data"
        git push